=== spryker/oms/data/definition/oms-01.xsd
<?xml version="1.0"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="spryker:oms-01"
    attributeFormDefault="unqualified"
    elementFormDefault="qualified">

    <xsd:element name="statemachine" type="statemachineType"/>

    <xsd:complexType name="processType" mixed="true">
        <xsd:sequence>
            <xsd:element type="subprocessesType" name="subprocesses" minOccurs="0"/>
            <xsd:element type="statesType" name="states" minOccurs="0"/>
            <xsd:element type="transitionsType" name="transitions" minOccurs="0"/>
            <xsd:element type="eventsType" name="events" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="name" use="optional"/>
        <xsd:attribute type="xsd:string" name="main" use="optional"/>
        <xsd:attribute type="xsd:string" name="file" use="optional"/>
        <xsd:attribute type="xsd:string" name="prefix" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="statesType">
        <xsd:sequence>
            <xsd:element type="stateType" name="state" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="transitionsType">
        <xsd:sequence>
            <xsd:element type="transitionType" name="transition" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="stateType" mixed="true">
        <xsd:sequence>
            <xsd:element name="flag" maxOccurs="unbounded" minOccurs="0">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="exclude from customer"/>
                        <xsd:enumeration value="exclude from invoice"/>
                        <xsd:enumeration value="ready for invoice"/>
                        <xsd:enumeration value="waiting for export"/>
                        <xsd:enumeration value="cancellable"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="name" use="required"/>
        <xsd:attribute type="xsd:string" name="display" use="optional"/>
        <xsd:attribute type="xsd:string" name="reserved" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="statemachineType" mixed="true">
        <xsd:sequence>
            <xsd:element type="processType" name="process" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="transitionType">
        <xsd:sequence>
            <xsd:element type="xsd:string" name="source"/>
            <xsd:element type="xsd:string" name="target"/>
            <xsd:element type="xsd:string" name="event" minOccurs="0"/>
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="happy" use="optional"/>
        <xsd:attribute type="xsd:string" name="condition" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="eventType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute type="xsd:string" name="name" use="required"/>
                <xsd:attribute type="xsd:string" name="timeout" use="optional"/>
                <xsd:attribute type="xsd:string" name="onEnter" use="optional"/>
                <xsd:attribute type="xsd:string" name="manual" use="optional"/>
                <xsd:attribute type="xsd:string" name="command" use="optional"/>
                <xsd:attribute type="xsd:string" name="timeoutProcessor" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="subprocessesType">
        <xsd:sequence>
            <xsd:element name="process" maxOccurs="unbounded" minOccurs="0">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string"/>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="eventsType">
        <xsd:sequence>
            <xsd:element type="eventType" name="event" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== spryker/oms/tests/_data/state-machine/subprocesses/sub01.xml
<?xml version="1.0"?>
<statemachine
    xmlns="spryker:oms-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:oms-01 http://static.spryker.com/oms-01.xsd"
>

    <process name="sub01">
        <states>
            <state name="payment preparations" reserved="true"/>
            <state name="awaiting approval"/>
        </states>

        <transitions>
            <transition happy="true">
                <source>new</source>
                <target>awaiting approval</target>
                <event>wait</event>
            </transition>

            <transition>
                <source>awaiting approval</source>
                <target>payment preparations</target>
                <event>prepare payment</event>
            </transition>

            <transition happy="true">
                <source>payment preparations</source>
                <target>payment pending</target>
                <event>authorize</event>
            </transition>
        </transitions>

        <events>
            <event name="prepare payment" manual="true"/>
            <event name="wait" manual="true"/>
        </events>
    </process>

</statemachine>

=== spryker/oms/tests/SprykerTest/Zed/Oms/Business/Util/ActiveProcessFetcher/Fixtures/Sub/ActiveSubProcess.xml
<?xml version="1.0"?>
<statemachine
    xmlns="spryker:oms-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:oms-01 http://static.spryker.com/oms-01.xsd"
>

    <process name="ActiveSubProcess">

        <states>
            <state name="returned" display="sub process state display value"/>
            <state name="refunded"/>
        </states>

        <transitions>
            <transition>
                <source>paid</source>
                <target>returned</target>
                <event>return</event>
            </transition>

            <transition>
                <source>returned</source>
                <target>refunded</target>
                <event>refund</event>
            </transition>
        </transitions>

        <events>
            <event name="return" manual="true"/>
            <event name="refund" manual="true"/>
        </events>
    </process>

</statemachine>

=== spryker/oms/tests/SprykerTest/Zed/Oms/Business/Util/ActiveProcessFetcher/Fixtures/ActiveStateMachine.xml
<?xml version="1.0"?>
<statemachine
    xmlns="spryker:oms-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:oms-01 http://static.spryker.com/oms-01.xsd"
>

    <process name="ActiveStateMachine" main="true">
        <subprocesses>
            <process>ActiveSubProcess</process>
        </subprocesses>

        <states>
            <state name="new" reserved="true" display="name display value"/>
            <state name="payment pending" reserved="true"/>
            <state name="paid"/>
        </states>

        <transitions>
            <transition>
                <source>new</source>
                <target>payment pending</target>
                <event>authorize</event>
            </transition>

            <transition>
                <source>payment pending</source>
                <target>paid</target>
                <event>pay</event>
            </transition>

        </transitions>

        <events>
            <event name="authorize" onEnter="true"/>
            <event name="pay" manual="true"/>
        </events>
    </process>

    <process name="ActiveSubProcess" file="Sub/ActiveSubProcess.xml"/>

</statemachine>

=== spryker/oms/tests/_data/state-machine/Test02.xml
<?xml version="1.0"?>
<statemachine
    xmlns="spryker:oms-01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="spryker:oms-01 http://static.spryker.com/oms-01.xsd"
>

    <process name="Test02" main="true">

        <states>
            <state name="new" reserved="true"/>
            <state name="payment pending" reserved="true"/>
            <state name="invalid">
                <flag>exclude from customer</flag>
            </state>
            <state name="cancelled">
                <flag>exclude from customer</flag>
            </state>
            <state name="paid" reserved="true"/>
            <state name="exported" reserved="true"/>
            <state name="shipped" reserved="true"/>
            <state name="delivered"/>
            <state name="closed"/>
        </states>

        <transitions>
            <transition happy="true">
                <source>new</source>
                <target>payment pending</target>
                <event>authorize</event>
            </transition>

            <transition>
                <source>new</source>
                <target>invalid</target>
                <event>authorization-failed</event>
            </transition>

            <transition>
                <source>payment pending</source>
                <target>cancelled</target>
                <event>pay</event>
            </transition>

            <transition happy="true">
                <source>paid</source>
                <target>exported</target>
                <event>export</event>
            </transition>

            <transition happy="true">
                <source>exported</source>
                <target>shipped</target>
                <event>ship</event>
            </transition>

            <transition happy="true">
                <source>shipped</source>
                <target>delivered</target>
                <event>stock-update</event>
            </transition>

            <transition happy="true">
                <source>delivered</source>
                <target>closed</target>
                <event>close</event>
            </transition>

        </transitions>

        <events>
            <event name="authorize" manual="true"/>
            <event name="authorization-failed" manual="true"/>
            <event name="pay" manual="true" timeout="1 hour"/>
            <event name="export" manual="true"/>
            <event name="ship" manual="true"/>
            <event name="stock-update" manual="true"/>
            <event name="close" manual="true" timeout="1 hour"/>
            <event name="return" manual="true"/>
        </events>
    </process>

</statemachine>
